# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OLED add-on
version: "0.0.1"
slug: oled
description: Use OLED screens via i2c
url: "https://github.com/wildekek/ha-addons/tree/main/oled"
stage: experimental
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
services: 
  - mqtt:need
init: false
apparmor: false
full_access: true
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-22
map:
  - config:rw
options:
  message: "Hello world!"
  display_interface_serial: i2c
  display_interface_port: 1
  display_interface_address: 60
  display_type: sh1106
  display_rotate: "2"
schema: 
  message: str
  display_interface_serial: list(i2c)
  display_interface_port: int
  display_interface_address: int
  display_type: list(sh1106)
  display_rotate: list(0|1|2|3)
#image: "ghcr.io/home-assistant/{arch}-addon-example"